allowedMedia:
- advertising
- anime
- animeandmanga
- animatedfilm
- animatedfilms
- animation
- arg
- asiananimation
- audio
- audioplay
- author
- blog
- bollywood
- book
- cardgame
- cardgames
- comicbook
- comicbooks
- comic
- comics
- comicstrip
- composer
- creator
- dcanimateduniversediscworld
- disney
- disneyandpixar
- dreamworks
- dungeonsanddragons
- easternanimation
- fairytales
- fanfic
- fanfics
- fanfiction
- fanwork
- fanworks
- film
- films
- fokelore
- folklore
- folkloreandfairytales
- franchise
- gamebooks
- jokes
- larp
- letsplay
- lightnovel
- literature
- liveaction
- liveactionfilm
- liveactionfilms
- liveactiontv
- machinima
- manga
- manhua
- manhwa
- manhwaandmanhua
- magazine
- magazines
- marvelcinematicuniverse
- media
- music
- musicvideos
- myth
- mythandreligion
- mythology
- mythologyandreligion
- mythsandreligion
- newmedia
- newspapercomic
- newspapercomics
- other
- pinball
- podcast
- printmedia
- professionalwrestling
- prowrestling
- puppetshows
- radio
- reallife
- recordedandstandupcomedyreligion
- religionandmythology
- roleplay
- roleplayinggames
- script
- series
- sports
- standupcomedy
- tabletop
- tabletoprpg
- tabletopgame
- tabletopgames
- tabletopgaming
- television
- theater
- theatre
- themeparks
- toys
- troperworks
- videogame
- videogames
- visualnovel
- visualnovels
- webanimation
- webcomic
- webcomics
- webcreator
- webgames
- webmedia
- weboriginal
- website
- webvideo
- webvideos
- westernanimation
- wiki
- wrestling

ignoredTypes:
# Ignore languages other than English (for now)
- de
- eo
- es
- fi
- fr
- hu
- it
- itadministrivia
- itdarthwiki
- itsugarwiki
- 'no'
- pl
- pt
- ro
- se

# Ignore YMMV type namespaces
- aatafovs
- accidentalnightmarefuel
- alternativecharacterinterpretation
- andthefandomrejoiced
- analysis
- awesome
- awesomebosses
- awesomebutimpractical
- awesomemusic
- badass
- betterthanitsounds
- fetishfuel
- fridge
- fridgebrilliance
- fridgehorror
- funny
- headscratchers
- heartwarming
- highoctanenightmarefuel
- horrible
- narm
- nightmarefuel
- shockingelimination
- thatoneboss
- thescrappy
- whatanidiot
- ymmv

# Ignored types that we may add in future
- allblue
- shoutout
- usefulnotes
- whamepisode

# Ignore TVtropes pages not relevant to project
- administrivia
- charactersheets
- characters
- community
- cowboybebopathiscomputer
- creatorkiller
- crimeandpunishmentseries
- darthwiki
- dieforourship
- directlinetotheauthor
- drinkinggame
- encounters
- fanficrecs
- fannickname
- fishytheascendant
- funwithacronyms
- gush
- haiku
- hellisthatnoise
- hoyay
- imagelinks
- images
- imagesource
- justforfun
- madmanentertainment
- masseffect
- memes
- pantheon
- quotes
- recap
- referencedby
- ride
- sandbox
- selfdemonstrating
- slidingscale
- soyouwantto
- sugarwiki
- thatoneboss
- trivia
- tropeco
- tropers
- tropertales
- troubledproduction
- turnofthemillennium
- warpthataesop
- wmg
- workpagesinmain
- monster
- wallbangers

knownAliases:
  BuffyTheVampireSlayer: Buffy
